services:
  grafana:
    image: grafana/grafana:12.1.0
    container_name: grafana-mcpclient-ci
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_DEFAULT_APP_MODE=development
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=cisco-mcpclient-app
    volumes:
      - ./dist:/var/lib/grafana/plugins/cisco-mcpclient-app
      - ./provisioning:/etc/grafana/provisioning
